### PR TITLE
starter code

### PR DESCRIPTION
**Pull request by Ben-Rumbold**
Pushing initial starter code (HTML, CSS and JavaScript)

### CODE REVIEW

**Comment by 6nhuseyin** [comment]
Starter code is iplemented

**Review by 6nhuseyin — APPROVED** [review]
The starter codes are implemented

**Review by DariaMS1 — APPROVED** [review]
Approving starter code from feature/ben-starter-code to main branch.

**Comment by DariaMS1** [comment]
Comment test from the bottom of the page.

**Comment by Ben-Rumbold** [comment]
Now going to merge

**Pull request closed without merging**
